//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Haber()
        {
            this.Begenmes = new HashSet<Begenme>();
            this.Favorites = new HashSet<Favorite>();
            this.Yorums = new HashSet<Yorum>();
            this.Uploads = new HashSet<Upload>();
            this.Paylasims = new HashSet<Paylasim>();
        }
    
        public int haber_id { get; set; }
        public string haber_name { get; set; }
        public Nullable<int> tiklanma_s { get; set; }
        public Nullable<int> begeni_s { get; set; }
        public Nullable<int> paylasim_s { get; set; }
        public Nullable<int> yorum_s { get; set; }
        public string haber_turu { get; set; }
        public Nullable<int> kategory_id { get; set; }
        public string haber_url { get; set; }
        public string haber_aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Begenme> Begenmes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Upload> Uploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paylasim> Paylasims { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
