//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTU1Entities : DbContext
    {
        public BTU1Entities()
            : base("name=BTU1Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Begenme> Begenmes { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Haber> Habers { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Paylasim> Paylasims { get; set; }
        public virtual DbSet<Upload> Uploads { get; set; }
        public virtual DbSet<Uye> Uyes { get; set; }
        public virtual DbSet<Yorum> Yorums { get; set; }
        public virtual DbSet<Haber2> Haber2 { get; set; }
    }
}
