//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B1.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public Nullable<System.DateTime> u_trh { get; set; }
        public Nullable<System.TimeSpan> u_saat { get; set; }
        public int u_id { get; set; }
        public Nullable<int> haber_id { get; set; }
        public Nullable<int> uye_id { get; set; }
        public Nullable<System.DateTime> haber2_trh { get; set; }
    
        public virtual Haber Haber { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
